// import {createConstants} from '../../common/utils'
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER        = "LOGOUT_USER";
export const GETTING_CAPTCHA        = "GETTING_CAPTCHA";
export const GET_CAPTCHA_SUCCESS       = "GET_CAPTCHA_SUCCESS";

export const GET_CAPTCHA_FAILURE       = "GET_CAPTCHA_FAILURE";




export const FETCH_PROTECTED_DATA_REQUEST = "FETCH_PROTECTED_DATA_REQUEST";
export const RECEIVE_PROTECTED_DATA = "RECEIVE_PROTECTED_DATA";
